[package]
name = "dsh-llm"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
dsh-cordis = { path = "../cordis" }
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
async-trait.workspace = true
uuid.workspace = true
regex.workspace = true